#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: 322119169559-hsh9i72f6cf2ecjv2fjcer74ceofi4oq.apps.googleusercontent.com
#            clientSecret: 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
#sever:
#  port: 8082